# Generated by Django 5.0.6 on 2024-07-25 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "date_inscription",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lien", models.URLField(null=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "utilisateur_qrcode",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qrcodes",
                        to="ScanMaster.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartageQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_partage", models.DateTimeField(auto_now_add=True)),
                (
                    "qrcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="ScanMaster.qrcode",
                    ),
                ),
                (
                    "utilisateur_cible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_recus",
                        to="ScanMaster.utilisateur",
                    ),
                ),
                (
                    "utilisateur_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_envoyes",
                        to="ScanMaster.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_scan", models.DateTimeField(auto_now_add=True)),
                ("device", models.CharField(max_length=255)),
                (
                    "qrcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="ScanMaster.qrcode",
                    ),
                ),
                (
                    "utilisateur_historique",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_scan",
                        to="ScanMaster.utilisateur",
                    ),
                ),
            ],
        ),
    ]
