# Generated by Django 5.0.6 on 2024-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QRQUOI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
