# Generated by Django 5.0.6 on 2024-06-16 22:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QRQUOI", "0002_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="date_creation",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="lien",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="qrcode",
            name="utilisateur_qrcode",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qrcodes",
                to="QRQUOI.utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
        migrations.CreateModel(
            name="HistoriqueScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_scan", models.DateTimeField(auto_now_add=True)),
                ("device", models.CharField(max_length=255)),
                (
                    "qrcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="QRQUOI.qrcode",
                    ),
                ),
                (
                    "utilisateur_historique",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_scan",
                        to="QRQUOI.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartageQR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_partage", models.DateTimeField(auto_now_add=True)),
                (
                    "qrcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages",
                        to="QRQUOI.qrcode",
                    ),
                ),
                (
                    "utilisateur_cible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_recus",
                        to="QRQUOI.utilisateur",
                    ),
                ),
                (
                    "utilisateur_source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partages_envoyes",
                        to="QRQUOI.utilisateur",
                    ),
                ),
            ],
        ),
    ]
